function bic = bayesian_information_criterion(numpars,index,expname,see,params)

%% Importing Experimental Variables
gad = exp_data(numpars,index,expname);

stime = gad.stdp_time;
stdp_fun = gad.stdp_fun;
n = length(stdp_fun);
p = gad.num_var;


rtdp_fun = integration( ...
    stime',...
    params(1),...
    params(2),...
    params(3),...
    params(4),...
    params(5),...
    params(6),...
    params(7),...
    params(8),...
    params(9),...
    params(10),...
    params(11))';


% % normalization
% stdp_fun = (stdp_fun - mean(stdp_fun))/std(stdp_fun)
%

E = sum( (stdp_fun - rtdp_fun).^2 ) / (n -1) ;
bic = n*log(E) + p*log(n)

data_file= fopen('bics','a');
fprintf(data_file, '%s %d %d %d %f \n', expname, numpars, index, see, bic );

