function y = fitting(x,gad)

params = [0 x];

gap = gad.scale_gap(gad.pidx+1);
b   = gad.scale_b(gad.pidx+1);
params = gap.*params(gad.pidx+1) + b;


stime = gad.stdp_time;
stdp_fun = gad.stdp_fun;
n = length(stdp_fun);
p = gad.num_var;


rtdp_fun = integration( ...
    stime',...
    params(1),...
    params(2),...
    params(3),...
    params(4),...
    params(5),...
    params(6),...
    params(7),...
    params(8),...
    params(9),...
    params(10),...
    params(11))';
 
% Fraction of variance unexplained
y = (sum( (stdp_fun - rtdp_fun).^2 ) / sum( (stdp_fun - mean(stdp_fun)).^2 ));


