function y = integration(time_d,decay_rate1,decay_rate2,coeff_K,gpp,gnp,gpn,gnn,eps,esp,ens,esn)

decay_rate=[decay_rate1 decay_rate2];

y = zeros(size(time_d));

if ( decay_rate(1) >= decay_rate(2) )
    ind_y = 1;
    for t_d = time_d
        if ( t_d <= -decay_rate(2) )
            y(ind_y) =  gnn*dwnnl(t_d,decay_rate,coeff_K) ... 
                      + gpn*dwpnl(t_d,decay_rate,coeff_K) ...
                      + esn*dwsnl(t_d,decay_rate,coeff_K) ...
                      + ens*dwnsl(t_d,decay_rate,coeff_K) ...
                      + eps*dwpsl(t_d,decay_rate,coeff_K);
        elseif ( t_d <= 0 )
            y(ind_y) = gpp*dwppl(t_d,decay_rate,coeff_K) ...
                     + gnn*dwnnl(t_d,decay_rate,coeff_K) ...
                     + gpn*dwpnh(t_d,decay_rate,coeff_K) ...
                     + esn*dwsnh(t_d,decay_rate,coeff_K) ...
                     + ens*dwnsl(t_d,decay_rate,coeff_K) ...
                     + esp*dwspl(t_d,decay_rate,coeff_K) ...
                     + eps*dwpsl(t_d,decay_rate,coeff_K);
        elseif ( t_d <= decay_rate(1) - decay_rate(2) )
            y(ind_y) = gpp*dwppmr(t_d,decay_rate,coeff_K) ...
                     + gnn*dwnnl(t_d,decay_rate,coeff_K) ... 
                     + gpn*dwpnh(t_d,decay_rate,coeff_K) ... 
                     + esn*dwsnh(t_d,decay_rate,coeff_K) ...
                     + ens*dwnsl(t_d,decay_rate,coeff_K) ...
                     + esp*dwsph(t_d,decay_rate,coeff_K) ...
                     + eps*dwpsh(t_d,decay_rate,coeff_K);
        elseif ( t_d <= decay_rate(1) )
            y(ind_y) = gpp*dwpph(t_d,decay_rate,coeff_K) ...
                     + gnn*dwnnh(t_d,decay_rate,coeff_K) ...
                     + gnp*dwnpl(t_d,decay_rate,coeff_K) ...
                     + esn*dwsnh(t_d,decay_rate,coeff_K) ...
                     + ens*dwnsl(t_d,decay_rate,coeff_K) ...
                     + esp*dwsph(t_d,decay_rate,coeff_K) ...
                     + eps*dwpsh(t_d,decay_rate,coeff_K);
        else
            y(ind_y) = gnn*dwnnh(t_d,decay_rate,coeff_K) ...
                     + gnp*dwnph(t_d,decay_rate,coeff_K) ...
                     + esn*dwsnh(t_d,decay_rate,coeff_K) ...
                     + ens*dwnsh(t_d,decay_rate,coeff_K) ...
                     + esp*dwsph(t_d,decay_rate,coeff_K);
        end
        ind_y = ind_y + 1;
    end
else
    ind_y = 1;
    for t_d = time_d
        if ( t_d <= -decay_rate(2) )
            y(ind_y) = gnn*dwnnl(t_d,decay_rate,coeff_K) ...
                     + gpn*dwpnl(t_d,decay_rate,coeff_K) ...
                     + esn*dwsnl(t_d,decay_rate,coeff_K) ... 
                     + ens*dwnsl(t_d,decay_rate,coeff_K) ... 
                     + eps*dwpsl(t_d,decay_rate,coeff_K);
        elseif ( t_d <= decay_rate(1) - decay_rate(2) )
            y(ind_y) = gpp*dwppl(t_d,decay_rate,coeff_K) ... 
                     + gnn*dwnnl(t_d,decay_rate,coeff_K) ... 
                     + gpn*dwpnh(t_d,decay_rate,coeff_K) ... 
                     + esn*dwsnh(t_d,decay_rate,coeff_K) ... 
                     + ens*dwnsl(t_d,decay_rate,coeff_K) ... 
                     + esp*dwspl(t_d,decay_rate,coeff_K) ... 
                     + eps*dwpsl(t_d,decay_rate,coeff_K);
        elseif ( t_d <= 0 )
            y(ind_y) = gpp*dwppml(t_d,decay_rate,coeff_K) ... 
                     + gnn*dwnnh(t_d,decay_rate,coeff_K) ... 
                     + gnp*dwnpl(t_d,decay_rate,coeff_K) ... 
                     + esn*dwsnh(t_d,decay_rate,coeff_K) ... 
                     + ens*dwnsl(t_d,decay_rate,coeff_K) ... 
                     + esp*dwspl(t_d,decay_rate,coeff_K) ... 
                     + eps*dwpsl(t_d,decay_rate,coeff_K);
        elseif ( t_d <= decay_rate(1) )
            y(ind_y) = gpp*dwpph(t_d,decay_rate,coeff_K) ... 
                     + gnn*dwnnh(t_d,decay_rate,coeff_K) ... 
                     + gnp*dwnpl(t_d,decay_rate,coeff_K) ... 
                     + esn*dwsnh(t_d,decay_rate,coeff_K) ... 
                     + ens*dwnsl(t_d,decay_rate,coeff_K) ... 
                     + esp*dwsph(t_d,decay_rate,coeff_K) ... 
                     + eps*dwpsh(t_d,decay_rate,coeff_K);
        else
            y(ind_y) = gnn*dwnnh(t_d,decay_rate,coeff_K) ... 
                     + gnp*dwnph(t_d,decay_rate,coeff_K) ... 
                     + esn*dwsnh(t_d,decay_rate,coeff_K) ... 
                     + ens*dwnsh(t_d,decay_rate,coeff_K) ... 
                     + esp*dwsph(t_d,decay_rate,coeff_K);
        end
        ind_y = ind_y + 1;
    end
end
